global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'asset-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['asset-service:8080']

  - job_name: 'alert-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['alert-service:8080']

  - job_name: 'telemetry-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['telemetry-service:8080']

  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service:8080']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
