server:
  port: 8080

spring:
  application:
    name: gateway-service

  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    gateway:
      routes:

        - id: asset-service
          uri: http://asset-service:8080
          predicates:
            - Path=/asset/**
          filters:
            - StripPrefix=1

        - id: alert-service
          uri: http://alert-service:8080
          predicates:
            - Path=/alert/**
          filters:
            - StripPrefix=1

        - id: telemetry-service
          uri: http://telemetry-service:8080
          predicates:
            - Path=/telemetry/**
          filters:
            - StripPrefix=1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Asset Service
        url: /asset/v3/api-docs
      - name: Alert Service
        url: /alert/v3/api-docs
      - name: Telemetry Service
        url: /telemetry/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
